init_args: 
  _target_: models.retrievers.dense.Dense
  model_name: "Snowflake/snowflake-arctic-embed-l"
  max_len: 256
  pooler:
    _target_: models.retrievers.dense.ClsPooler
  similarity: 
    _target_: models.retrievers.dense.CosineSim
  prompt_q: "Represent this sentence for searching relevant passages: "
batch_size: 512
batch_size_sim: 2048