init_args: 
  _target_: models.retrievers.dense.Dense
  model_name: "jinaai/jina-embeddings-v2-base-en"
  max_len: 256
  pooler:
    _target_: models.retrievers.dense.MeanPooler
  similarity: 
    _target_: models.retrievers.dense.CosineSim
batch_size: 512
batch_size_sim: 2048