init_args: 
  _target_: models.retrievers.dense.Dense
  model_name: "nomic-ai/nomic-embed-text-v1.5"
  max_len: 256
  pooler:
    _target_: models.retrievers.dense.MeanPooler
  similarity: 
    _target_: models.retrievers.dense.CosineSim
  prompt_q: "search_query: "
  prompt_d: "search_document: "
batch_size: 512
batch_size_sim: 2048