init_args: 
  _target_: models.retrievers.splade.Splade
  model_name: naver/efficient-splade-VI-BT-large-doc
  query_encoder_name: naver/efficient-splade-VI-BT-large-query
  max_len: 128
batch_size: 512
batch_size_sim: 512