generate_test_samples: 10
test_size_ratio: 0.01
trainer:
  dataloader_num_workers: 4
  eval_accumulation_steps: 16
  gradient_accumulation_steps: 1
  num_train_epochs: 1
  weight_decay: 0.1
  warmup_ratio: 0.05
  learning_rate: 5e-5
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 4
  bf16: True
  report_to: "wandb"