train:
    doc: 
        init_args:
            _target_: modules.dataset_processor.UT1Docs
            split: "fake"
    
    query: 
        init_args:
            _target_: modules.dataset_processor.UT1Queries
            split: "faketrain"
dev:
    doc: 
        init_args:
            _target_: modules.dataset_processor.UT1Docs
            split: "fake"
    
    query: 
        init_args:
            _target_: modules.dataset_processor.UT1Queries
            split: "faketest"

test:
    doc: 
        init_args:
            _target_: modules.dataset_processor.UT1Docs
            split: "fake"
    
    query: 
        init_args:
            _target_: modules.dataset_processor.UT1Queries
            split: "faketest"

